BUGFIX. The github action to build and test Node.js version 12 does not work.
Error:
- Gets an error because the default npm script 'test' is also not allowed.
Error: no test has been specified.

Solution:
- Remove the npm script 'test' from the 'package.json' file.